/* File game_const.h */
#ifndef GAME_CONST_H
#define GAME_CONST_H

#define GAME_SPEED 1.0
#define ATTACK_SPEED 7.5
#define ASTEROIDS_FREQ 5.0
#define BURNING_TIME 2.0

#define ASTEROID_SIZE 25.0*SCALE
#define ASTEROID_SPEED 250.0*SCALE
#define ASTEROID_EXPANSION 100.0*SCALE
#define ASTEROID_ROTATION_SPEED 100.0

#define BULLET_WIDTH 2.0*SCALE
#define BULLET_HEIGHT 20.0*SCALE
#define BULLET_SPEED 500.0*SCALE

#define PLAYER_SPEED 500.0*SCALE
#define PLAYER_TURN_SPEED 100.0

#define LIFE_SIZE 25.0*SCALE
#define LIFE_GAP 5.0*SCALE

#define SCORE_WIDTH 25.0*SCALE
#define SCORE_DEGREE ((float)HEIGHT/(float)MAX_SCORE)

#endif
/* GAME_CONST_H */
